ai:
  search_depth: 3
  use_lookahead: true
  move_time_limit: 2.0

evaluation:
  checkmate_bonus: 1000
  check_bonus: 10
  capture_bonus: 3
  center_control_bonus: 1

game:
  ai_vs_ai: false  # New config option
  human_color: random  # random/white/black

analysis_rules:
  preferred_openings: ["e4", "d4"]
  avoid_early_queen: true
  avoid_early_king: true
  max_pawn_advance: 3
  hanging_piece_bonus: 2.0
  passed_pawn_bonus: 1.5