# config.yaml
# Configuration for pure evaluation-based chess AI

game:
  ai_vs_ai: true              # Set to true for AI vs AI matches
  human_color: random           # Options: white, black, random

ai:
  search_depth: 5              # Minimax search depth (1-5 recommended)
  use_quiescence: true         # 
  use_lookahead: true          # Enable minimax with alpha-beta pruning
  move_time_limit: 5.0         # Maximum time per move in seconds
  move_ordering: true          # Enable move ordering for better pruning

evaluation:
  # Material values and bonuses
  checkmate_bonus: 1000        # Bonus for checkmate threats
  check_bonus: 10              # Bonus for giving check
  in_check_penalty: -10        # Penalty for being in check
  king_threat_penalty: -5      # Penalty for being checked
  capture_bonus: 3             # Base bonus for captures
  center_control_bonus: 1      # Bonus per center square controlled
  castling_bonus: 5            # Bonus for castling rights
  king_safety_bonus: 0.5       # Bonus per pawn in king shield
  en_passant_bonus: 1          # Bonus for en passant opportunity
  pawn_promotion_bonus: 5      # Bonus for pawn promotion
  passed_pawn_bonus: 0.25
  hanging_piece_bonus: 2       # Bonus for attacking hanging pieces
  trapped_piece_penalty: -5    # Penalty for trapped pieces
  piece_development_bonus: 2   # Bonus for developing minor pieces
  piece_development_penalty: -0.5  # Penalty for under-developed minor pieces
  piece_activity_bonus: 0.1
  knight_pair_bonus: 1         # Bonus for having knight pair
  knight_vision_penalty: -0.25
  pawn_advancement_bonus: 0.25
  rook_development_penalty: 0.2
  castling_protection_bonus: 3
  castling_protection_penalty: -6
  repetition_penalty: -100     # Penalty for threefold repetition
  pst_weight: 1.2
  material_weight: 0.8
  bishop_vision_bonus: 1
  
  # Piece activity multipliers
  knight_activity_multiplier: 0.1    # Multiplier per square attacked by knight
  bishop_activity_multiplier: 0.15   # Multiplier per square attacked by bishop
  
  # Advanced evaluation features
  enable_piece_square_tables: true  # Use piece-square tables for positional eval
  enable_pawn_structure: true        # Evaluate pawn structure
  enable_king_safety_detailed: true  # Detailed king safety evaluation
  
# Performance settings
performance:
  max_moves_evaluated: 50      # Limit moves evaluated per position
  use_transposition_table: false  # Cache evaluations (not implemented yet)
  parallel_evaluation: false      # Parallel move evaluation (not implemented yet)

# Debug settings
debug:
  print_evaluations: false     # Print evaluation details to console
  save_evaluation_log: false   # Save detailed evaluation log
  show_thinking_time: true     # Display time taken for move calculation