# Test simulation configuration
# This is a simplified configuration for testing the game simulation manager

# Maximum number of simulations to run in parallel.
max_concurrent_simulations: 2

# Disable central data storage for testing
use_central_storage: false

simulations:
  # Simple test simulation
  - name: "Quick Test - V7P3R vs. Stockfish (Skill 1)"
    games_to_run: 2  # Just run 2 games for quick testing
    chess_game:
      game_config:
        ai_vs_ai: true
        human_color: 'white'
        game_type: standard
        rated: true
      white_engine_config:
        engine: 'v7p3r'
        engine_type: 'deepsearch'
      black_engine_config:
        engine: 'stockfish'
    v7p3r:
      v7p3r:
        ruleset: 'default_evaluation'
        depth: 3
    stockfish_handler:
      stockfish:
        skill_level: 1
