{
  "training": {
    "batch_size": 32,
    "learning_rate": 0.001,
    "epochs": 15,
    "weight_decay": 0.001,
    "rule_weight": 0.8,
    "patience": 5,
    "grad_clip_max_norm": 1.0
  },
  "game": {
    "ai_vs_ai": false,
    "human_color": "random"
  },
  "analysis_rules": {
    "preferred_openings": ["e4", "d4"],
    "avoid_early_queen": true,
    "max_pawn_advance": 3,
    "hanging_piece_bonus": 2.0,
    "passed_pawn_bonus": 1.5
  }
}
