# config/puzzle_config.yaml
# Configuration file for the chess puzzle solver and database

puzzle_database:
  db_path: "puzzles/puzzle_data.db"
  
  # Puzzle selection parameters
  selection:
    min_rating: 800  # Minimum puzzle ELO
    max_rating: 3000  # Maximum puzzle ELO
    batch_size: 50  # Number of puzzles to fetch at once
    themes: []  # Optional list of themes to filter by
    
  # Adaptive ELO settings
  adaptive_elo:
    enabled: true
    starting_elo: 1200
    increment: 100  # ELO increase after successful puzzles
    decrement: 50   # ELO decrease after failed puzzles
    success_threshold: 0.8  # Success rate required to increase difficulty
    
  # Database maintenance
  maintenance:
    auto_vacuum: true
    max_attempts_per_puzzle: 10  # Maximum number of attempts to store per puzzle

puzzle_solver:
  # Engine settings for puzzle solving
  engine:
    depth: 10  # Default search depth for puzzle solving
    time_limit: 5000  # Time limit in ms for each move
    
  # Tracking and reporting
  tracking:
    record_attempts: true
    save_positions: true
    
  # Integration with other systems
  integration:
    update_transposition_table: true  # Add solved puzzles to transposition table
    stockfish_verification: true  # Verify solutions with Stockfish
    
  # Display and logging
  display:
    show_solution: false  # Whether to show the solution after failure
    verbose_logging: true
