adaptive_mutation: false
crossover_rate: 0.8
cuda_batch_size: 8
elitism_rate: 0.5
generations: 1
max_stagnation: 1
max_workers: 1
mutation_rate: 0.1
neural_model_path: null
population_size: 2
positions_count: 2
positions_source: random
stockfish_config:
  debug_mode: false
  depth: 1
  elo_rating: 100
  max_depth: 1
  movetime: 50
  skill_level: 1
  stockfish_path: engine_utilities/external_engines/stockfish/stockfish-windows-x86-64-avx2.exe
use_cuda: false
use_multiprocessing: false
use_neural_evaluator: false
