# chess_game_config.yaml
# Configuration for the automated game handler
# This is where pygame chess game settings are configured, as well as the white and black engine paths to use for the game. Additional configurations for those engines will be in engine_utilities/external_engines/<engine_name>_handler.yaml

# game_config settings
game_config:

  # General game settings
  game_type: standard            # Options: standard, chess960, king_of_the_hill, three_check, antichess, atomic, racing_kings
  game_clock: 0                  # Time in seconds for each player, 0 for no clock
  game_increment: 0              # Increment in seconds per move, 0 for no increment
  rated: true                    # Set to true to record game and move metrics for analysis.

  # AI vs AI game_config settings
  ai_vs_ai: true                 # Set to true for AI vs AI matches
  ai_game_count: 1               # Number of games to play in AI vs AI mode
  starting_position: default     # Default starting position name (or FEN string)
  white_engine: v7p3r            # Name of the engine being used (e.g., 'v7p3r', 'stockfish'), this value is a direct reference to the engine configuration values in their respective config files
  black_engine: stockfish        # sets this colors engine configuration name, same as above, important note that if the engines are set the same then only whites metrics will be collected to prevent negation in win loss metrics

  # AI vs Human game_config settings
  human_color_pref: random            # Options: white, black, random (for human vs AI)              


  