# Configuration for engine_utilities modules
# Includes settings for database management, cloud storage, and client-server communication

# Database configuration
database:
  path: "metrics/chess_metrics.db"
  backup_interval_hours: 24
  max_size_mb: 1000  # Alert if database exceeds this size

# Cloud storage configuration
cloud:
  enabled: false  # Set to true to enable cloud storage
  bucket_name: "viper-chess-engine-data"  # GCS bucket name
  firestore_collection: "games"  # Firestore collection for game data
  raw_collection: "raw_simulations"  # Firestore collection for raw simulation data
  upload_retry_count: 5
  upload_retry_delay_seconds: 1

# Server configuration
server:
  host: "0.0.0.0"  # Listen on all interfaces
  port: 8080
  request_timeout_seconds: 30
  max_request_size_mb: 100

# Client configuration
client:
  server_url: "http://localhost:8080"  # Default server URL
  max_retries: 3
  retry_delay: 1  # Base delay in seconds (uses exponential backoff)
  offline_buffer_path: "logging/offline_buffer.json"
  auto_flush_interval_minutes: 10  # How often to try reconnecting when offline

# ETL configuration
etl:
  schedule: "0 0 * * *"  # Daily at midnight (cron format)
  batch_size: 100  # Process this many games per batch
  timeout_minutes: 120  # Max runtime for ETL job
