# simulation_config.yaml
# Main configuration for the Game Simulation Manager

# Maximum number of simulations to run in parallel.
# Defaults to the number of CPU cores if not specified.
max_concurrent_simulations: 4

# Enable central data storage for simulation results
# When enabled, results will be sent to the configured server in engine_utilities.yaml
use_central_storage: true

# Predefined simulation types
simulation_templates:
  - id: "stockfish_elo_finder"
    name: "Stockfish ELO Finder"
    description: "Determines the ELO rating of the V7P3R engine by playing adaptive matches against Stockfish"
    type: "adaptive_elo"
    config:
      initial_elo: 1500
      min_elo: 800
      max_elo: 3200
      adjustment_factor: 1.0
      convergence_threshold: 0.05
      min_games_for_convergence: 20
      max_games: 100

simulations:
  - name: "V7P3R (Aggressive) vs. Stockfish (Skill 5)"
    games_to_run: 2 # Number of games to play with this configuration
    chess_game:
      white_engine_config:
        engine: 'v7p3r'
        engine_type: 'deepsearch'
      black_engine_config:
        engine: 'stockfish'
        # Stockfish settings are inside stockfish_handler.yaml, but can be overridden
    v7p3r:
      v7p3r: # Corresponds to the engine name key in v7p3r_config.yaml
        ruleset: 'aggressive_evaluation'
        depth: 4
    stockfish_handler:
      stockfish_config:
        skill_level: 5

  - name: "V7P3R (Conservative) vs. V7P3R (Aggressive)"
    games_to_run: 2
    chess_game:
      white_engine_config:
        engine: 'v7p3r'
        engine_type: 'deepsearch'
        ruleset: 'conservative_evaluation' # Can also be specified here
      black_engine_config:
        engine: 'v7p3r'
        engine_type: 'deepsearch'
        ruleset: 'aggressive_evaluation'
    v7p3r:
      # No overrides needed if we specify everything in chess_game config's engine_config
      # But we can override base engine parameters if we want
      v7p3r:
        depth: 3
