# v7p3r_rl_engine/v7p3r_rl_config.yaml
# Configuration file for the v7p3r Reinforcement Learning (RL) engine.

# RL hyperparameters
learning_rate: 0.001
hidden_dim: 128
gamma: 0.99
input_dim: 773
output_dim: 4672
max_moves: 200
# Add more RL-specific settings as needed